/**
 * Group Members: Luis Velascco, Larry Hong, Peter Alvarado Nunez.
 * Group Leader: Luis Velasco
 * Date: 11-05-2015
 * Course: IT 306 - 001
 * Class Activity 8
 */
package classActivity_8;

public class PQEntry {
	private long key; 
	private Flight val; 
	public static final long DEFAULT_KEY = 1000000; //Indicates a very low priority --used for non-connective flights.
	public PQEntry() {}
	
	public void setValue(Flight p){ 
		val = p;
		calcKey();
	}
	
	/**
	 * Method to calculate the key that determines the priority of each flight. The key is calculated by
	 * multiplying the connection period times a value depending if is a connection flight or not.
	 */
	private void calcKey(){
		//If the flight is not a connecting flight then the key is generated by multiplying
		//2 * the connection period.
		if(!val.isConnectingFlight()){			
			key = 2 * val.getConnectionPeriod();
		//If the flight is a connecting flight then the key is generated by multiplying
		//1 * the connection period.
		}else if(val.isConnectingFlight()){
			key = 1 * val.getConnectionPeriod();			
		}
	}
	
	public Flight getValue(){
		return val;
	}
	
	public long getKey(){
		return key; 
	}
	
	public String toString() {
		return "Value: "+ val.toString() + ", key: "+ key;
	}
}